
name: thesis-environment
channels:
  - conda-forge
dependencies:
  - python=3.5.6
  - numpy=1.14.2
  - pip
  - pip:
    - pandas==0.18.0
    - scipy==1.3.0
    - joblib==0.13.2
    - matplotlib==3.0.0
    - seaborn==0.9.0
    - scikit-learn==0.21.2
    - astropy
